// src/pages/404.vue
<template>
  <Layout>
    <div class="container-inner mx-auto py-16 text-center">
      <h2 class="text-2xl font-bold border-b-4 border-orange-600 inline p-4">Page Not Found</h2>
      <g-image src="../../static/404.svg" class="mt-32" />
    </div>
  </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: "Page Not Found"
  }
};
</script>

// www/src/routes/404.svelte
<svelte:head>
  <title>Khrome.dev - Page Not Found</title>
</svelte:head>

<div class="container-inner mx-auto py-16 text-center">
  <h2 class="text-2xl font-bold border-b-4 border-orange-600 inline p-4">
    Page Not Found
  </h2>
  <img
    src="https://res.cloudinary.com/khromedotdev/image/upload/c_scale,w_auto:100,dpr_auto,f_auto,q_auto/v1570448524/custom_404_kgq3ro.png"
    alt="Man reading map"
    class="mt-32" />
</div>
