// www/src/routes/blog/index.svelte
<script context="module">
  export async function preload({ params, query }) {
    const res = await this.fetch(`blog.json`);
    const data = await res.json();

    if (res.status === 200) {
      return { data: data };
    } else {
      this.error(res.status, data.message);
    }
  }
</script>

<script>
  import TheNewsletter from "../../components/TheNewsletter.svelte";
  export let data;
</script>

<!---
  TODO:
    - Title
    - Description
    - Twitter Card
    - OG Setup
    - JSON+LD
      - https://jsonld-examples.com/schema.org/code/blog-markup.php
-->
<svelte:head>
  <title>Blog</title>
</svelte:head>

<div
  class="bg-regal-blue text-white overflow-hidden bg-repeat min-h-20"
  style="background-image: linear-gradient(to bottom, rgba(40,69,105,0)
  0%,rgba(36,60,90,1) 80%), url('./dots.svg');" />
<div
  class="container-inner mx-auto -mt-48 mb-16 relative bg-white pt-4
  sm:rounded-t-lg sm:px-8 sm:pt-8">
  {#each data.posts as { attributes, slug, timeToRead }}
    <div class="post border-gray-400 border-b mb-12">
      {#if attributes.cover_image}
        <a href="/blog/{slug}">
          <img
            alt="Cover image"
            class="w-full mx-auto mb-8 rounded-lg"
            src={attributes.cover_image} />
        </a>
      {/if}
      <h2 class="text-3xl font-bold">
        <a href="/blog/{slug}" class="text-copy-primary">{attributes.title}</a>
      </h2>
      <div class="text-copy-secondary mb-4">
        <span>{attributes.date}</span>
        <span class="pl-4 pr-4 inline-block">&middot;</span>
        <span>{timeToRead} min read</span>
      </div>

      <div class="text-lg mb-4">{attributes.description}</div>

      <div class="mb-8">
        <a href="/blog/{slug}" class="font-bold uppercase">Read More</a>
      </div>
    </div>
  {/each}

  <!-- PAGINATION GOES HERE -->

</div>
<TheNewsletter />

// src/pages/Blog.vue
<template>
  <Layout>
    <div
      class="bg-regal-blue text-white overflow-hidden bg-repeat min-h-20"
      style="background-image: linear-gradient(to bottom, rgba(40,69,105,0) 0%,rgba(36,60,90,1) 80%), url('./dots.svg');"
    ></div>
    <div
      class="container-inner mx-auto -mt-48 mb-16 relative bg-white pt-4 sm:rounded-t-lg sm:px-8 sm:pt-8"
    >
      <div
        v-for="post in $page.posts.edges"
        :key="post.id"
        class="post border-gray-400 border-b mb-12"
      >
        <g-link :to="post.node.path">
          <g-image
            alt="Cover image"
            v-if="post.node.cover_image"
            class="w-full mx-auto mb-8 rounded-lg"
            :src="post.node.cover_image"
          />
        </g-link>
        <h2 class="text-3xl font-bold">
          <g-link :to="post.node.path" class="text-copy-primary">{{ post.node.title }}</g-link>
        </h2>
        <div class="text-copy-secondary mb-4">
          <span>{{ post.node.date }}</span>
          <span class="pl-4 pr-4 inline-block">&middot;</span>
          <span>{{ post.node.timeToRead }} min read</span>
        </div>

        <div class="text-lg mb-4">{{ post.node.description }}</div>

        <div class="mb-8">
          <g-link :to="post.node.path" class="font-bold uppercase">Read More</g-link>
        </div>
      </div>
      <!-- end post -->

      <pagination-posts
        v-if="$page.posts.pageInfo.totalPages > 1"
        base="/blog"
        :totalPages="$page.posts.pageInfo.totalPages"
        :currentPage="$page.posts.pageInfo.currentPage"
      />
    </div>
    <the-newsletter />
  </Layout>
</template>

<page-query>
query Posts ($page: Int) {
  posts: allPost (sortBy: "date", order: DESC, perPage: 10, page: $page) @paginate {
    totalCount
    pageInfo {
      totalPages
      currentPage
    }
    edges {
      node {
        id
        title
        path
        cover_image
        tags {
          id
          title
          path
        }
        date (format: "MMMM D, Y")
        timeToRead
        description
      }
    }
  }
}
</page-query>

<script>
// cover_image (width: 770, height: 380, blur: 10)
import TheNewsletter from "../components/TheNewsletter";
import PaginationPosts from "../components/PaginationPosts";
export default {
  components: {
    PaginationPosts,
    TheNewsletter
  },
  metaInfo: {
    title: "Blog"
  }
};
</script>
