// www/src/components/MyWorks.svelte
<script>
  import one from "../../static/dots-one.svg";
  import two from "../../static/dots-two.svg";
  import three from "../../static/dots-three.svg";
  import four from "../../static/dots-four.svg";
</script>

<div class="bg-white text-black overflow-hidden relative">
  <div
    class="container-inner mx-auto py-16 pb-8 text-center textl-xl relative z-10">
    <div class="container-inner mx-auto text-xl pb-4 relative">
      <h2
        class="text-2xl font-bold border-b-4 border-orange-600 inline p-4"
        id="works">
        My Works
      </h2>

      <ul class="text-lg sm:text-xl text-left mt-16">
        <li class="checkmark mb-12 relative">
          <div class="absolute top-1/2 left-0">
            {@html one}
          </div>
          <div class="pl-16">Director of Technology for Inside Rx</div>
          <div class="pl-16 text-lg text-gray-600">
            I am currently responsible for the technology organization of a
            startup. I oversee several teams that span multiple consumer-facing
            digital properties.
          </div>
        </li>
        <li class="checkmark mb-12 relative">
          <div class="absolute top-1/2 left-0">
            {@html two}
          </div>
          <div class="pl-16">Senior Developer for Rig Up</div>
          <div class="pl-16 text-lg text-gray-600">
            I did a short stint at a startup that is changing the oil and gas
            industry. I built an optimizations platform and worked on improving
            the user experience.
            <em>#TooManyButtonDesigns</em>
          </div>
        </li>
        <li class="checkmark mb-12 relative">
          <div class="absolute top-1/2 left-0">
            {@html three}
          </div>
          <div class="pl-16">
            UI &amp; Solution Architect for General Motors
          </div>
          <div class="pl-16 text-lg text-gray-600">
            Oversaw the solution design and development powering the next
            generation of CMS platform. I managed the technical relationship
            with outside design agencies.
          </div>
        </li>
        <li class="checkmark mb-12 relative">
          <div class="absolute top-1/2 left-0">
            {@html four}
          </div>
          <div class="pl-16">Senior Developer for Army Research Labs</div>
          <div class="pl-16 text-lg text-gray-600">
            The job was mostly
            <span class="text-orange-500 line-through">cowboy</span>
            contract development. I worked on a variety of internal tools and
            web properties, including analytics trackers, custom calendars,
            WebGL powered apps, and more.
          </div>
        </li>
      </ul>
      <img
        src="developer.svg"
        alt="hero"
        class="mx-auto ml-auto mr-auto md:max-w-md" />
    </div>
  </div>
</div>

// src/components/MyWorks.vue
<template>
  <div class="bg-white text-black overflow-hidden relative">
    <div class="container-inner mx-auto py-16 pb-8 text-center textl-xl relative z-10">
      <div class="container-inner mx-auto text-xl pb-4 relative">
        <h2 class="text-2xl font-bold border-b-4 border-orange-600 inline p-4" id="works">My Works</h2>

        <ul class="text-lg sm:text-xl text-left mt-16">
          <li class="checkmark mb-12 relative">
            <div class="absolute top-1/2 left-0">
              <svg
                fill="#eeeeee"
                width="30pt"
                height="30pt"
                version="1.1"
                viewBox="0 0 100 100"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="m70 50c0 11.047-8.9531 20-20 20s-20-8.9531-20-20 8.9531-20 20-20 20 8.9531 20 20"
                />
              </svg>
            </div>
            <div class="pl-16">Director of Technology for Inside Rx</div>
            <div
              class="pl-16 text-lg text-gray-600"
            >I am currently responsible for the technology organization of a startup. I oversee several teams that span multiple consumer-facing digital properties.</div>
          </li>
          <li class="checkmark mb-12 relative">
            <div class="absolute top-1/2 left-0">
              <svg
                fill="#eeeeee"
                width="60pt"
                height="60pt"
                version="1.1"
                viewBox="0 0 100 100"
                xmlns="http://www.w3.org/2000/svg"
                style="margin-left: -1.25rem; margin-top: -1.25rem;"
              >
                <path
                  d="m50 45c-5.5234 0-10-4.4766-10-10s4.4766-10 10-10 10 4.4766 10 10-4.4766 10-10 10zm0 30c-5.5234 0-10-4.4766-10-10s4.4766-10 10-10 10 4.4766 10 10-4.4766 10-10 10z"
                />
              </svg>
            </div>
            <div class="pl-16">Senior Developer for Rig Up</div>
            <div class="pl-16 text-lg text-gray-600">
              I did a short stint at a startup that is changing the oil and gas industry. I built an optimizations platform and worked on improving the user experience.
              <em>#TooManyButtonDesigns</em>
            </div>
          </li>
          <li class="checkmark mb-12 relative">
            <div class="absolute top-1/2 left-0">
              <svg
                fill="#eeeeee"
                width="80pt"
                height="80pt"
                version="1.1"
                viewBox="0 0 100 100"
                xmlns="http://www.w3.org/2000/svg"
                style="margin-left: -2rem; margin-top: -2rem;"
              >
                <g>
                  <path
                    d="m50.102 53.301c-4.1016 0-7.5 3.3008-7.5 7.5s3.3008 7.5 7.5 7.5c4.1016 0 7.5-3.3008 7.5-7.5s-3.4023-7.5-7.5-7.5z"
                  />
                  <path
                    d="m45 39.301c0-4.1016-3.3008-7.5-7.5-7.5s-7.5 3.3008-7.5 7.5 3.3008 7.5 7.5 7.5 7.5-3.4023 7.5-7.5z"
                  />
                  <path
                    d="m62.5 31.801c-4.1016 0-7.5 3.3008-7.5 7.5s3.3008 7.5 7.5 7.5 7.5-3.3008 7.5-7.5-3.3984-7.5-7.5-7.5z"
                  />
                </g>
              </svg>
            </div>
            <div class="pl-16">UI &amp; Solution Architect for General Motors</div>
            <div
              class="pl-16 text-lg text-gray-600"
            >Oversaw the solution design and development powering the next generation of CMS platform. I managed the technical relationship with outside design agencies.</div>
          </li>
          <li class="checkmark mb-12 relative">
            <div class="absolute top-1/2 left-0">
              <svg
                fill="#eeeeee"
                width="40pt"
                height="40pt"
                version="1.1"
                viewBox="0 0 100 100"
                xmlns="http://www.w3.org/2000/svg"
                style="margin-left: -0.15rem; margin-top: -0.85rem;"
              >
                <g>
                  <path
                    d="m31.102 46.801c-8.6992 0-15.699-7-15.699-15.699 0-8.6992 7-15.699 15.699-15.699 8.6992 0 15.699 7 15.699 15.699 0 8.6992-7 15.699-15.699 15.699z"
                  />
                  <path
                    d="m68.5 46.801c-8.6992 0-15.699-7-15.699-15.699 0-8.6992 7-15.699 15.699-15.699s15.699 7 15.699 15.699c0 8.6992-7 15.699-15.699 15.699z"
                  />
                  <path
                    d="m31.102 84.199c-8.6992 0-15.699-7-15.699-15.699s7-15.699 15.699-15.699c8.6992 0 15.699 7 15.699 15.699 0 8.6016-7 15.699-15.699 15.699z"
                  />
                  <path
                    d="m68.5 84.199c-8.6992 0-15.699-7-15.699-15.699s7-15.699 15.699-15.699 15.699 7 15.699 15.699c0 8.6016-7 15.699-15.699 15.699z"
                  />
                </g>
              </svg>
            </div>
            <div class="pl-16">Senior Developer for Army Research Labs</div>
            <div class="pl-16 text-lg text-gray-600">
              The job was mostly
              <span class="text-orange-500 line-through">cowboy</span> contract development. I worked on a variety of internal tools and web properties, including analytics trackers, custom calendars, WebGL powered apps, and more.
            </div>
          </li>
        </ul>
        <g-image
          src="../../static/developer.svg"
          alt="hero"
          class="mx-auto ml-auto mr-auto md:max-w-md"
        />
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>
